import type { PokemonEntry } from '@/types/pokemon'

const cache = new Map<number, PokemonEntry[]>()

/* eslint-disable @typescript-eslint/ban-ts-comment */
// These JSON shards are generated by `npm run fetch-data` and won't exist until then.
const generationImports: Record<number, () => Promise<{ default: PokemonEntry[] }>> = {
  // @ts-ignore
  1: () => import('@/data/pokemon-gen-1.json'),
  // @ts-ignore
  2: () => import('@/data/pokemon-gen-2.json'),
  // @ts-ignore
  3: () => import('@/data/pokemon-gen-3.json'),
  // @ts-ignore
  4: () => import('@/data/pokemon-gen-4.json'),
  // @ts-ignore
  5: () => import('@/data/pokemon-gen-5.json'),
  // @ts-ignore
  6: () => import('@/data/pokemon-gen-6.json'),
  // @ts-ignore
  7: () => import('@/data/pokemon-gen-7.json'),
  // @ts-ignore
  8: () => import('@/data/pokemon-gen-8.json'),
  // @ts-ignore
  9: () => import('@/data/pokemon-gen-9.json'),
}

export async function loadGeneration(genId: number): Promise<PokemonEntry[]> {
  const cached = cache.get(genId)
  if (cached) return cached

  const loader = generationImports[genId]
  if (!loader) throw new Error(`Unknown generation: ${genId}`)

  const mod = await loader()
  const entries = mod.default as PokemonEntry[]
  cache.set(genId, entries)
  return entries
}

export async function loadActiveGenerations(activeGenerations: number[]): Promise<PokemonEntry[]> {
  const chunks = await Promise.all(activeGenerations.map(loadGeneration))
  return chunks.flat()
}
